on: [workflow_dispatch]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: LabyrinthRepo

      - name: Setup .NET9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
          
      - name: Checkout raylib
        uses: actions/checkout@v3
        with:
          ref: 5.5
          repository: raysan5/raylib
          path: RaylibRepo
          
#      - name: Install wasm-tools
#        run: |
#          dotnet workload install wasm-tools
#
#     - name: Setup emsdk
#        uses: mymindstorm/setup-emsdk@v11
#
#      - name: Build raylib for Web
#        run: |
#          cd RaylibRepo
#          emcmake cmake \
#            -B artifacts \
#            -D BUILD_EXAMPLES=Off \
#            -D PLATFORM=Web
#          cmake --build artifacts
#          cp artifacts/raylib/libraylib.a $GITHUB_WORKSPACE/LabyrinthRepo/Labyrinth/Wasm/raylib.a
#          
      - name: Publish dotnet project
        run: |
            cd LabyrinthRepo/
            dotnet publish -c Release /p:DefineConstants=WASM

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: LabyrinthRepo/Labyrinth/bin/Release/net9.0/browser-wasm/AppBundle
