on: [workflow_dispatch]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Publish dotnet project
        run: |
            cd Labyrinth/
            dotnet publish -c Release /p:DefineConstants=WASM

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: Labyrinth/bin/Release/net9.0/browser-wasm/AppBundle
